version: '3.9'

services:
  postgres14_read2:
    image: postgres:14
    container_name: postgres14_read2
    networks:
      read2_net:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=read2
    volumes:
      - postgres14_read2_data:/var/lib/postgresql/data

  read2:
    image: 'r1-j87'
    container_name: read2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres14_read2:5432/read2
    ports:
      - "8080:8080"
    networks:
      read2_net:
    depends_on:
      - postgres14_read2


networks:
  read2_net:
    driver: bridge

volumes:
  postgres14_read2_data:
