server:
  servlet:
    context-path: /api/read2/
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.com
    port: 465
    protocol: smtps
    username:
    password:

  datasource:
    first:
      url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
      driverClassName: org.h2.Driver
      username: sa
      password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: UTF-8
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
        query:
          plan_cache_max_size: 32
          plan_parameter_metadata_max_size: 16
          in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
    open-in-view: false


app:
  notificationComment: false
  notificationSingUp: false
  host: ${HOST:http://localhost:8080}

jwt:
  expiration: 1500

qualifier:
  allPostfix: Query
  post: PostServiceQueryImpl
  comment: CommentServiceQueryImpl

logging:
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    auth-service-first: debug
    org.hibernate: error
  logback:
    rollingpolicy:
      max-file-size: 1MB
      clean-history-on-start: on
      max-history: 2
  file:
    name: #s.log




